# Generated by Django 4.1.5 on 2023-01-31 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("username", models.CharField(max_length=255)),
                ("password", models.CharField(max_length=16)),
            ],
        ),
    ]
