# Generated by Django 4.1.5 on 2023-02-02 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_email"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table="account_user",
        ),
    ]
