# Generated by Django 4.1.5 on 2023-02-02 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0003_alter_user_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="user",
            table=None,
        ),
    ]
