# Generated by Django 4.1.5 on 2023-02-08 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0004_alter_user_table"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone",
            field=models.CharField(default="123", max_length=255),
        ),
    ]
