# Generated by Django 4.1.5 on 2023-02-08 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0005_user_phone"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(max_length=255),
        ),
    ]
