# Generated by Django 4.1.5 on 2023-01-23 10:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                ("company_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=55)),
                ("location", models.CharField(max_length=255)),
                ("about", models.TextField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IT", "IT"),
                            ("Non IT", "Non IT"),
                            ("Mobile Phones", "Mobile Phones"),
                        ],
                        max_length=100,
                    ),
                ),
                ("added_date", models.DateTimeField(auto_now=True)),
                ("active", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Employee",
            fields=[
                ("emp_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=155)),
                ("email", models.CharField(max_length=255)),
                ("address", models.CharField(max_length=255)),
                ("phone", models.CharField(max_length=10)),
                ("about", models.TextField()),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("Manager", "Manager"),
                            ("Software Dev", "Software Dev"),
                            ("HR", "HR"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "c_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="api.company"
                    ),
                ),
            ],
        ),
    ]
