# Generated by Django 4.1.5 on 2023-02-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Otp",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
                ("otp", models.CharField(max_length=4)),
            ],
        ),
    ]
