# Generated by Django 4.1.5 on 2023-02-03 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendemail", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="otp",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name="otp",
            name="modified_at",
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
