# Generated by Django 4.1.5 on 2023-02-03 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sendemail", "0002_otp_created_at_otp_modified_at"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="otp",
            table="send_otp",
        ),
    ]
