# Generated by Django 4.1.5 on 2023-02-03 10:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sendemail", "0003_alter_otp_table"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="otp",
            table=None,
        ),
    ]
