# Generated by Django 4.1.5 on 2023-02-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sendemail", "0004_alter_otp_table"),
    ]

    operations = [
        migrations.CreateModel(
            name="OnetimePassword",
            fields=[
                ("id", models.BigAutoField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255)),
                ("otp", models.CharField(max_length=4)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("modified_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name="Otp",
        ),
    ]
